[package]
name = "beegone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.64"
serde = { version = "1.0.183", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
typeshare = "1.0.1"
wasm-bindgen = "0.2.87"
