[package]
name = "beegone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasm-bindgen"]
wasm-bindgen = ["dep:wasm-bindgen", "serde"]

[dependencies]
js-sys = "0.3.64"
serde = { version = "1.0.182", features = ["derive"], optional = true }
serde-wasm-bindgen = "0.5.0"
thiserror = "1.0.44"
wasm-bindgen = { version = "0.2.87", optional = true }
