[package]
name = "beegone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm-bindgen = ["dep:wasm-bindgen", "js-sys", "serde"]

[dependencies]
js-sys = { version = "0.3.64", optional = true }
serde = { version = "1.0.182", features = ["derive"], optional = true }
serde-wasm-bindgen = "0.5.0"
thiserror = "1.0.44"
wasm-bindgen = { version = "0.2.87", optional = true }
