/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_action_free: (a: number, b: number) => void;
export const __wbg_get_action_move: (a: number) => number;
export const __wbg_get_action_spawn: (a: number) => number;
export const action_move: (a: number, b: number) => [number, number, number];
export const action_spawn: (a: number, b: number) => number;
export const __wbg_wasmmoveaction_free: (a: number, b: number) => void;
export const __wbg_get_wasmmoveaction_from: (a: number) => number;
export const __wbg_get_wasmmoveaction_to: (a: number) => number;
export const __wbg_wasmspawnaction_free: (a: number, b: number) => void;
export const __wbg_get_wasmspawnaction_on: (a: number) => number;
export const __wbg_get_wasmspawnaction_spawn: (a: number) => number;
export const __wbg_bee_free: (a: number, b: number) => void;
export const __wbg_get_bee_color: (a: number) => number;
export const __wbg_get_bee_species: (a: number) => number;
export const bee_new: (a: number, b: number) => number;
export const __wbg_board_free: (a: number, b: number) => void;
export const board_get: (a: number, b: number) => [number, number, number];
export const board_positions: () => [number, number, number];
export const __wbg_piece_free: (a: number, b: number) => void;
export const __wbg_get_piece_bee: (a: number) => number;
export const x: (a: number) => [number, number, number];
export const y: (a: number) => [number, number, number];
export const distance: (a: number, b: number) => [number, number, number];
export const __wbg_state_free: (a: number, b: number) => void;
export const __wbg_get_state_board: (a: number) => number;
export const state_new: () => [number, number, number];
export const state_actionsFrom: (a: number, b: number) => [number, number, number, number];
export const state_perform: (a: number, b: number) => [number, number, number];
export const __wbg_get_state_turn: (a: number) => number;
export const __wbindgen_export_0: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
