/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_moveaction_free: (a: number, b: number) => void;
export const __wbg_spawnaction_free: (a: number, b: number) => void;
export const __wbg_bee_free: (a: number, b: number) => void;
export const __wbg_pos_free: (a: number, b: number) => void;
export const __wbg_get_pos_q: (a: number) => number;
export const __wbg_set_pos_q: (a: number, b: number) => void;
export const __wbg_get_pos_r: (a: number) => number;
export const __wbg_set_pos_r: (a: number, b: number) => void;
export const __wbg_piece_free: (a: number, b: number) => void;
export const __wbg_board_free: (a: number, b: number) => void;
export const __wbg_state_free: (a: number, b: number) => void;
export const __wbg_action_free: (a: number, b: number) => void;
export const __wbg_actionerror_free: (a: number, b: number) => void;
export const stateNew: (a: number) => number;
export const stateActionsFrom: (a: number, b: number) => [number, number];
export const submitAction: (a: number) => any;
export const stateProgress: (a: number) => any;
export const boardGet: (a: number, b: number) => number;
export const boardPositions: () => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_export_3: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure88_externref_shim: (a: number, b: number, c: any) => void;
export const closure100_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
